/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../../index";

/**
 * @example
 *     {}
 */
export interface LipsyncListGenerationsRequest {
    /**
     * Filter generations by status
     */
    status?: Sync.GenerationStatus;
}
