/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Active speaker detection configuration
 */
export interface ActiveSpeaker {
    /** Whether to automatically detect and apply generation to the active speaker */
    auto_detect?: boolean;
}
