/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Recorded/Captured audio input
 */
export interface Audio {
    type: "audio";
    /** URL of the audio to be used for generation */
    url: string;
}
