/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface BatchResponse {
    id: Sync.BatchId;
    /** The date and time the batch was created. */
    created_at: string;
    /** The current status of the batch. */
    status: Sync.BatchStatus;
    /** Metrics about the batch processing progress. */
    metrics: Sync.BatchMetrics;
    /** The webhook URL for batch status notifications. */
    webhookUrl?: string;
    /** The URL to download the batch results file (available when completed). */
    outputUrl: string;
}
