/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the batch processing.
 */
export type BatchStatus = "PENDING" | "JOBS_CREATED" | "PROCESSING" | "COMPLETED" | "FAILED";
export const BatchStatus = {
    Pending: "PENDING",
    JobsCreated: "JOBS_CREATED",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Failed: "FAILED",
} as const;
