/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BatchMetrics {
    /** Total number of generation requests in the batch. */
    total_generations: number;
    /** Number of successfully completed generations. */
    success_count: number;
    /** Number of failed generations. */
    failed_count: number;
    /** Number of generations still pending or processing. */
    pending_count: number;
}
