/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface CreateGenerationDto {
    /** name of the model to use for generation. */
    model: Sync.Model;
    /** Array of input objects. Must include one video input item and one audio input item. Audio input items can be provided as either: recorded/captured audio url or a text-to-speech input with tts provider configuration. */
    input: Sync.Input[];
    /** additional options available for generation. */
    options?: Sync.GenerationOptions;
    /** webhook url for generation status updates. once the generation completes we will send a POST request to the webhook url with the generation data. */
    webhookUrl?: string;
    /** Base filename for the generated output without extension. The .mp4 extension will be added automatically.  Only alphanumeric characters, underscores, and hyphens are allowed, up to 255 characters. */
    outputFileName?: string;
}
