/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ElevenLabs {
    name: "elevenlabs";
    /** id of the voice to be used for generation */
    voiceId: string;
    /** script to be used for generation */
    script: string;
}
