/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface GenerationOptions {
    /** Defines how to handle duration mismatches between video and audio inputs. See the [Media Content Tips](/compatibility-and-tips/media-content-tips#sync-mode-options) guide for a brief overview,  or the SyncMode enum below for detailed explanations of each option. */
    sync_mode?: Sync.SyncMode;
    /** option to control how expressive lipsync can be. 0 -> least expressive, 1 -> most expressive. default:0.5 */
    temperature?: number;
    /** Active speaker detection configuration. When enabled, automatically detects and applies lipsync only to the active speaker in videos with multiple people. */
    active_speaker_detection?: Sync.ActiveSpeaker;
    /** Whether to detect occlusion during generation, slows down generation speed. */
    occlusion_detection_enabled?: boolean;
}
