/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface GenerationError {
    /** A message describing the error. */
    message: Sync.GenerationErrorMessage;
    /** The type of error that occurred. */
    statusCode: number;
}
