/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface GenerationOptions {
    /** lipsync mode when audio and video durations are out of sync. By default if the audio and video durations are out of sync and audio is longer than video, the video will loop. Otherwise, the video will be cut off at the end of the audio. */
    sync_mode?: Sync.SyncMode;
    /** Whether to detect active speaker and apply generation to them */
    active_speaker?: boolean;
}
