/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface Generation {
    /** The date and time the generation was created. */
    createdAt: string;
    /** The error message if the generation failed. */
    error?: string;
    /** The error code if the generation failed. */
    error_code?: string;
    id: Sync.GenerationId;
    /** An array of input objects used for generation. */
    input: Sync.Input[];
    /** The name of the model used for generation. */
    model: Sync.Model;
    /** Options for the generation. */
    options?: Sync.GenerationOptions;
    /** The duration of the output media. */
    outputDuration?: number;
    /** The URL of the output media. */
    outputUrl?: string;
    /** The URL of the segment output media. */
    segmentOutputUrl?: string;
    /** The status of the generation. */
    status: Sync.GenerationStatus;
    /** The URL to the webhook endpoint. */
    webhookUrl?: string;
}
