/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

/**
 * An input item for a generation.
 */
export type Input = Sync.Video | Sync.Audio | Sync.Tts;
