/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * name of the model to use for generation.
 */
export type Model = "lipsync-2" | "lipsync-1.9.0-beta" | "lipsync-2-pro";
export const Model = {
    Lipsync2: "lipsync-2",
    Lipsync190Beta: "lipsync-1.9.0-beta",
    Lipsync2Pro: "lipsync-2-pro",
} as const;
