/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SyncMode = "loop" | "bounce" | "cut_off" | "silence" | "remap";
export const SyncMode = {
    Loop: "loop",
    Bounce: "bounce",
    CutOff: "cut_off",
    Silence: "silence",
    Remap: "remap",
} as const;
