/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defines how to handle duration mismatches between video and audio inputs. Each mode applies different strategies when the video and audio lengths don't match.
 */
export type SyncMode =
    /**
     * When video duration < audio duration, bounce (reverse playback) the video to match audio duration. Otherwise crop video to match audio duration. */
    | "bounce"
    /**
     * When video duration < audio duration, loop the video to match audio duration. Otherwise crop video to match audio duration. */
    | "loop"
    /**
     * When audio duration > video duration, cut off audio to match video duration. Otherwise crop video to match audio duration. */
    | "cut_off"
    /**
     * When video duration > audio duration, add silence to audio to match video duration. Otherwise crop video to match audio duration. */
    | "silence"
    /**
     * Slowdown or speed up video to match audio duration exactly. This maintains the full content of both video and audio by adjusting playback speed. */
    | "remap";
export const SyncMode = {
    Bounce: "bounce",
    Loop: "loop",
    CutOff: "cut_off",
    Silence: "silence",
    Remap: "remap",
} as const;
