/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

/**
 * Text to speech input
 */
export interface Tts {
    type: "text";
    /** Integration provider configuration */
    provider: Sync.TtsProviderConfig;
}
