/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TtsProviderConfig {
    /** name of the provider */
    name: string;
    /** script to be used for generation */
    script: string;
    /** id of the voice to be used for generation */
    voiceId: string;
}
