/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

/**
 * @example
 *     {
 *         status: Sync.WebhookStatus.Completed,
 *         createdAt: "2024-01-10T12:00:00Z",
 *         id: "asdas12312ada",
 *         input: [{
 *                 type: "audio",
 *                 url: "https://example.com/audio.mp3"
 *             }],
 *         model: Sync.Model.Lipsync2,
 *         error: "",
 *         options: {},
 *         outputDuration: 10,
 *         outputUrl: "https://example.com/output.mp4",
 *         webhookUrl: "https://example.com/webhook"
 *     }
 */
export interface GenerationNotification {
    /** The status of the generation */
    status: Sync.WebhookStatus;
    /** The date and time the generation was created */
    createdAt: string;
    id: Sync.GenerationId;
    /** The input items for the generation */
    input: Sync.Input[];
    model: Sync.Model;
    /** error message if the generation failed */
    error?: string;
    /** options used for the generation */
    options?: Sync.GenerationOptions;
    /** generated output media duration in seconds */
    outputDuration?: number;
    /** url of the generated output media */
    outputUrl?: string;
    /** url of the webhook server */
    webhookUrl?: string;
}
