/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../index";

export interface GenerationNotification {
    /** The status of the generation */
    status: Sync.WebhookStatus;
    /** The date and time the generation was created */
    createdAt: string;
    id: Sync.GenerationId;
    /** The input items for the generation */
    input: Sync.Input[];
    model: Sync.Model;
    /** error message if the generation failed */
    error?: string;
    /** options used for the generation */
    options?: Sync.GenerationOptions;
    /** generated output media duration in seconds */
    outputDuration?: number;
    /** url of the generated output media */
    outputUrl?: string;
    /** url of the webhook server */
    webhookUrl?: string;
}
