/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the webhook
 */
export type WebhookStatus = "COMPLETED" | "FAILED";
export const WebhookStatus = {
    Completed: "COMPLETED",
    Failed: "FAILED",
} as const;
