/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../index";

export type CreateGenerationDtoInputItem =
    | Sync.CreateGenerationDtoInputItem.Video
    | Sync.CreateGenerationDtoInputItem.Audio
    | Sync.CreateGenerationDtoInputItem.Text;

export namespace CreateGenerationDtoInputItem {
    export interface Video extends Sync.VideoInputItem {
        type: "video";
    }

    export interface Audio extends Sync.AudioInputItem {
        type: "audio";
    }

    export interface Text extends Sync.TextInputItem {
        type: "text";
    }
}
