/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * name of the model to use for generation.
 */
export type CreateGenerationDtoModel =
    | "lipsync-2"
    | "lipsync-1.9.0-beta"
    | "lipsync-1.8.0"
    | "lipsync-1.7.1"
    | "lipsync-1.6.0";
export const CreateGenerationDtoModel = {
    Lipsync2: "lipsync-2",
    Lipsync190Beta: "lipsync-1.9.0-beta",
    Lipsync180: "lipsync-1.8.0",
    Lipsync171: "lipsync-1.7.1",
    Lipsync160: "lipsync-1.6.0",
} as const;
