/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../index";

export interface CreateGenerationDto {
    /** name of the model to use for generation. */
    model: Sync.CreateGenerationDtoModel;
    /** Array of input objects. Must include one video input and either an audio or text input. */
    input: Sync.CreateGenerationDtoInputItem[];
    /** additional options available for generation. */
    options?: Sync.GenerationOptions;
    /** webhook url for generation status updates. once the generation completes we will send a POST request to the webhook url with the generation data. */
    webhookUrl?: string;
}
