/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EstimatedGenerationCost {
    /** The estimated frame count for the generation. */
    estimatedFrameCount: number;
    /** The estimated cost of the generation in USD. */
    estimatedGenerationCost: number;
}
