/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * lipsync mode when audio and video durations are out of sync.
 */
export type GenerationOptionsSyncMode = "loop" | "bounce" | "cut_off" | "silence" | "remap";
export const GenerationOptionsSyncMode = {
    Loop: "loop",
    Bounce: "bounce",
    CutOff: "cut_off",
    Silence: "silence",
    Remap: "remap",
} as const;
