/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * format of the output media that is generated.
 */
export type GenerationOptionsOutputFormat = "mp4" | "mov";
export const GenerationOptionsOutputFormat = {
    Mp4: "mp4",
    Mov: "mov",
} as const;
