/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the generation.
 */
export type GenerationStatus =
    | "PENDING"
    | "PROCESSING"
    | "COMPLETED"
    | "FAILED"
    | "REJECTED"
    | "CANCELED"
    | "TIMED_OUT";
export const GenerationStatus = {
    Pending: "PENDING",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Failed: "FAILED",
    Rejected: "REJECTED",
    Canceled: "CANCELED",
    TimedOut: "TIMED_OUT",
} as const;
