/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../index";

export interface Generation {
    /** A unique identifier for the generation. */
    id: string;
    /** The date and time the generation was created. */
    createdAt: string;
    /** The status of the generation. */
    status: Sync.GenerationStatus;
    /** The name of the model used for generation. */
    model: string;
    /** An array of input objects containing type and URL. */
    input: Sync.GenerationInputItem[];
    /** The URL to the webhook endpoint. */
    webhookUrl?: Record<string, unknown>;
    /** Options for the generation. */
    options?: Record<string, unknown>;
    /** The URL of the output media. */
    outputUrl?: Record<string, unknown>;
    /** The duration of the output media. */
    outputDuration?: Record<string, unknown>;
    /** The error message if the generation failed. */
    error?: string;
}
