/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../index";

export interface GenerationOptions {
    /** Padding values */
    pads?: number[];
    /** downscale inputs for faster generations. used to preview changes. */
    speedup?: number;
    /** generation temperature randomness between 0 and 1. note: only works for lipsync-2 based models. */
    temperature?: number;
    /** format of the output media that is generated. */
    output_format?: Sync.GenerationOptionsOutputFormat;
    /** lipsync mode when audio and video durations are out of sync. */
    sync_mode?: Sync.GenerationOptionsSyncMode;
    /** Frames per second (FPS) for the output video */
    fps?: number;
    /** Resolution of the output video [width, height] */
    output_resolution?: string[];
    /** Whether to detect active speaker and apply generation to them */
    active_speaker?: boolean;
}
