/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../index";

export interface TextInputItem {
    /** Integration provider */
    provider: Sync.ProviderItem;
}
