/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VideoInputItem {
    url: string;
    /** Start and end time in seconds for each video segment to apply generation to */
    segments_secs?: number[][];
    /** Start and end frames for each video segment to apply generation to */
    segments_frames?: number[][];
}
