/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         webhook_url: "https://your-webhook-url.com/batch-webhook",
 *         dry_run: false
 *     }
 *
 * @example
 *     {
 *         dry_run: true
 *     }
 */
export interface CreateBatchRequest {
    /** Optional webhook URL to receive batch completion notifications. A POST request will be sent when the batch completes or fails. */
    webhook_url?: string;
    /** When true, validates the input file without processing. Returns validation status without creating generations. */
    dry_run?: boolean;
}
