/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ListBatchesRequest {
    /**
     * Filter batches by status
     */
    status?: Sync.BatchStatus;
    /**
     * Filter batches created after this datetime (ISO 8601 format)
     */
    created_after?: string;
    /**
     * Filter batches created before this datetime (ISO 8601 format)
     */
    created_before?: string;
}
