/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sync from "../../../../index";

/**
 * @example
 *     {
 *         model: "lipsync-2"
 *     }
 */
export interface CreateGenerationRequest {
    model: Sync.Model;
    /** Array of input objects. Can be used to provide urls for larger files. Each input should either have a file or a url. Audio input items can be provided as either: recorded/captured audio url or a text-to-speech input with tts provider configuration. */
    input?: Sync.Input[];
    options?: Sync.GenerationOptions;
    webhookUrl?: string;
}
