/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Generate } from "./api/resources/generate/client/Client";

export declare namespace SyncClient {
    export interface Options {
        environment?: core.Supplier<environments.SyncEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class SyncClient {
    protected _generate: Generate | undefined;

    constructor(protected readonly _options: SyncClient.Options) {}

    public get generate(): Generate {
        return (this._generate ??= new Generate(this._options));
    }
}
