/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SyncEnvironment = {
    Default: "https://api.sync.so",
    Dev: "https://dev-api.sync.so",
} as const;

export type SyncEnvironment = typeof SyncEnvironment.Default | typeof SyncEnvironment.Dev;
